### ISSUE TITLE
从备份恢复后executor panic

### ISSUE THREAD

**Issue by rink1969** [cita-cloud/executor_evm#55]
```
2022-11-16T02:36:18.341522607+00:00 INFO executor - grpc port of executor_evm: 50002
2022-11-16T02:36:23.287518162+00:00 INFO executor::core_chain - current_height: 873
2022-11-16T02:36:23.287605547+00:00 INFO executor::core_executor::libexecutor::executor - executor init, current_height: 873, current_hash: 0x5ed4141f86f31748b143bf4af71bdfeb7ae47476fc26cd31838811e0ced2d24f
2022-11-16T02:36:23.288806374+00:00 INFO executor - start executor_evm grpc server
2022-11-16T02:36:23.288870565+00:00 INFO executor - metrics on
2022-11-16T02:36:23.288988117+00:00 INFO cloud_util::metrics - exporting metrics to http://0.0.0.0:60002/metrics
2022-11-16T02:36:23.327092496+00:00 ERROR executor::panic_hook -
============================
   0: executor::panic_hook::panic_hook
             at /build/src/[panic_hook.rs:39](http://panic_hook.rs:39/):21
   1: core::ops::function::Fn::call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/[function.rs:77](http://function.rs:77/):5
   2: std::panicking::rust_panic_with_hook
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:702](http://panicking.rs:702/):17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:588](http://panicking.rs:588/):13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/[backtrace.rs:138](http://backtrace.rs:138/):18
   5: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:584](http://panicking.rs:584/):5
   6: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/[panicking.rs:142](http://panicking.rs:142/):14
   7: executor::main::{{closure}}
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/[backtrace.rs:122](http://backtrace.rs:122/):18
   8: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/[mod.rs:514](http://mod.rs:514/):17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9
      std::panicking::try::do_call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:492](http://panicking.rs:492/):40
      std::panicking::try
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:456](http://panicking.rs:456/):19
      std::panic::catch_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panic.rs:137](http://panic.rs:137/):14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/[mod.rs:513](http://mod.rs:513/):30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/[function.rs:248](http://function.rs:248/):5
   9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/[boxed.rs:1940](http://boxed.rs:1940/):9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/[boxed.rs:1940](http://boxed.rs:1940/):9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17
  10: start_thread
  11: clone


position:
Thread <unnamed> panicked at receive call_req_receiver error: receiving on an empty and disconnected channel, src/[main.rs:206](http://main.rs:206/)
```

**Comment by rink1969** [comment]
panic之后微服务重启多次依然无法恢复。
重启整个节点之后恢复。

对比正常启动的日志
差别就是后面应该有一个： INFO cloud_util::metrics - register histogram controller_to_Exec succeeded 
可能跟metrics 注册有关。

**Comment by rink1969** [comment]
有可能是metrics里面unwrap了，这个是在 grpc server子线程中。
子线程退出，导致里面的sender句柄被销毁，进而导致另外一个线程中recv报错。

修复metrics实现，处理一下里面的unwrap。

**Comment by rink1969** [comment]
https://github.com/cita-cloud/cloud-common-rs/pull/2
